travis:
  secure:
    BINSTAR_TOKEN: O49p2WgKedA/2bsj9ewt2nB2tn9jcp5ClaAf8yCbIgE7t0jrE0ghfSvfq47+AUNikdmUZLV4qfN0n2rxeS++LZ35EPf0fBQurH1V+ubrrbHj1rGzhvHDHjAQlwA47X9mEx6mUCTsYb3RnXq8Jc9lYxWp9pt2kIyFm4vmVFvWbd//Q3vSTPc+1IIiHSRK7dzw8eT/HA4PB59XA6vT6ujGOf5UmO8//xF7/dUetKCcrjhE3qogB0NEBMJ9RBtfAIxfC8iRjJJx2qPZ+sSVPR7jis7RBJFK/R4x8rPLOqEoFVcmeKwAW345fvXqHFk1Dd1b7B4ww31ZnneHRIiW5ZPpTsGAZG2Zd56wyRd9vSWAptG5/2JT5toAkEn0bZgor2gU+ew66BEKp7HyouTCyfERgRYG4sxicMcuNwO9wkJCkd5fYyrXZKCez3VJFf3ZnhYBr05UVWfWuRrN3unPcbOLOuGQAupjOnwvvpx8Ya/EV1edXuAH86+uGCfg+riX7PdBR2f22CfrWizQ7QbbcOXu4LrLJJZjM92JrAN1v0pYmfLp98skbFT8dnvGLxmZnQw/MJ8n0iMw//kSLli3I92MAVVgCqTog+xtPnLQdjlCuBKrOUDbT7BWsfEOz/sP1au7eN21GMMqePCqhdje5XU16R92QVkQmGCqOjNJQ3ZMPMQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
